### ISSUE TITLE
Error: Not running when calling .read multiple times

### ISSUE THREAD

**Issue by patrick--** [patrick--/node-omron-fins#3]
```
var fins = require('omron-fins');
var port = 9600, ip = '192.168.250.1', options = {timeout: 10000};
var client = fins.FinsClient(port, ip);

// This does not read correctly
setTimeout(function(){
    client.read('D6029', 1);
}, 11000);
```
Results in this error:

```
/* The cases that do not read correctly give the following error
Missing error handler on `socket`.
Error: Not running
    at Socket._healthCheck (dgram.js:420:11)
    at Socket.send (dgram.js:272:8)
    at FinsClient.run (/var/lib/cloud9/MPFTraceServer/node_modules/omron-fins/lib/fins_client.js:324:17)
    at Socket.objCurrCycleTraceData.objProductionQty.SID (/var/lib/cloud9/MPFTraceServer/app_cycle.js:42:16)
    at Socket.emit (events.js:95:17)
    at Socket.onevent (/var/lib/cloud9/MPFTraceServer/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/var/lib/cloud9/MPFTraceServer/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/var/lib/cloud9/MPFTraceServer/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/var/lib/cloud9/MPFTraceServer/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/var/lib/cloud9/MPFTraceServer/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
*/
```

**Comment by patrick--** [comment]
Add a ```timeout``` event handler:

```
client.on('timeout', function(test){
	console.log("timed out");

});
client.on('error',function(error) {
  console.log("Error: ", error);
});

// Setting up the response listener
// Showing properties of a response
client.on('reply',function(msg) {
  var newDate = new Date();
  console.log(newDate);
  console.log("Reply from: ", msg.remotehost);
    console.log("SID: ", msg.sid);
    console.log("Replying to issued command of: ", msg.command);
    console.log("Response code of: ", msg.code);
    console.log("Data returned: ", msg.values);
});

//Read 10 registers starting at DM register 00000
//client.read('D00000',3);
setInterval(function() {
   client.read("D000000",1);
}, 11000);
```
